### PR TITLE
Restructurings and type dispatch clarifications

### PR DESCRIPTION
**Pull request by aartaka**
This is mostly prompted by Antero Mejr's type dispatching suggestion. I've also indulged in some restructurings while I was at it.

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Would you like me to declare a new draft, or is this too little change?

**Comment by aartaka** [comment]
Let's wait with the draft, I have some things brewing.

**Comment by arthurgleckler** [comment]
Sounds good.  I'll leave this un-merged until you tell me to.  I'm happy to merge and declare drafts independently or at the same time.

**Comment by aartaka** [comment]
Okay, this seems to be it for the changes I wanted to make to sections. More ambitious things can wait some more. Let's merge and declare a new draft.

**Comment by aartaka** [comment]
@arthurgleckler you can merge, thanks!

**Comment by arthurgleckler** [comment]
See #29.

**Pull request merged**
